version: "3"
services:
  mongo:
    image: mongo:3.6.17
    ports:
      - '27017:27017'
    command: --smallfiles
    environment:
      MONGO_INITDB_DATABASE: 'fleet-manager'
      MONGO_INITDB_ROOT_USERNAME: 'root'
      MONGO_INITDB_ROOT_PASSWORD: 'example'
    volumes:
      - ./backend/docker/mongo/volume/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  fleet-manager-service:
    build: ./backend/
    ports:
      - 8081:8081
    environment:
      MONGO_HOST: 'mongo'
      MONGO_DATABASE: 'fleet-manager'
      MONGO_USER: 'userdb'
      MONGO_PASS: 'UserPwd1234'
    depends_on:
      - mongo

volumes:
  mongo:
