version: 2
jobs:
  build_fleet_manager_service:
    docker:
      - image: circleci/openjdk:11-jdk

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m
        
    steps:
      - run : cd backend/ && mvn clean package
workflows:
  version: 2
  fleet_manager:
    jobs:
    - build_fleet_manager_service
