version: 2
jobs:
  build_fleet_manager_service:
    docker:
      - image: cicleci/openjdk:11-jdk

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m
        
    steps:
      - run : cd backend/ && mvn clean package
